# Generated by Django 4.2.5 on 2026-05-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon_name",
                    models.CharField(help_text="Lucide icon name", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("is_popular", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="exams.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Note"),
                            ("VIDEO", "Video Lesson"),
                            ("AUDIO", "Audio Summary"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PREMIUM", "Premium")],
                        max_length=10,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
                ),
                ("image_url", models.URLField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="exams.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category_tag",
                    models.CharField(
                        help_text="Short tag like PSC, SSC", max_length=50
                    ),
                ),
                ("content", models.TextField()),
                ("publish_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("is_new", models.BooleanField(default=True)),
                ("link", models.URLField(blank=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.exam",
                    ),
                ),
            ],
        ),
    ]
