# Generated by Django 4.2.5 on 2026-05-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_subject_questionpaper_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionpaper",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("ANNUAL", "Annual Exam"),
                    ("MODEL", "Model Exam"),
                    ("SUPPLEMENTARY", "Supplementary"),
                ],
                max_length=15,
            ),
        ),
    ]
